### ISSUE TITLE
Some guidance to install for Domoticz on RPI?

### ISSUE THREAD

**Issue by Domoberry** [ggraat/domoticz-easycontrol-plugin#2]
Not really an issue, other than my limited experience ...
Would there be any additional detail available on how to prepare for use with Domoticz on RPI?
e.g. your plugin.py should be copied to a (new) directory like /home/pi/domoticz/plugins/easycontrol, and the 'gateway' bosch-xmpp should be installed (nodejs and npm needed). 
Yet, there should also be some provision to ensure bosch-xmpp automatically obtains the needed credentials and that it is started in 'bridge' mode each time Domoticz/RPI boots up. How can that best be done?

**Comment by ggraat** [comment]
Hi, I have no experience with Domoticz on RPI, but I think you can use these instructions: https://www.domoticz.com/wiki/Using_Python_plugins#Example_for_Raspberry_Pi_with_Raspbian

For the bosch-xmpp part, I have a script that starts the bridge each time my device (in my case Synology NAS) is booted/restarted with the correct parameters. The credentials are set in environment variables in my system as described in https://github.com/robertklep/bosch-xmpp?tab=readme-ov-file#command-line-interface. After this, the Domoticz plugin can connect to it.

**Comment by Domoberry** [comment]
Thanks! Easycontrol CT200 is now available in Domoticz running on an RPI4.
Bosch-xmpp is running on the same RPI4.
I have used the 'systemd' tool to start bosch-xmpp with the needed credentials in bridge mode each time the RPI4 boots.
